package com.ifbk.project.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2014/4/22 下午 03:40:33 by Hibernate Tools 3.4.0.CR1

/**
 * Biln1 generated by hbm2java
 */
@Entity
@Table(name="BILN1")
public class Biln1 implements java.io.Serializable {

	@Id
	@Column(name="PAT")
	private String pat;
	
	@Column(name="SQ")
	private Integer sq;

	@Column(name="BIL_ID")
	private String bilId;
	

	public Biln1() {
	}

	public Biln1(String pat) {
		this.pat = pat;
	}

	public Biln1(String pat, Integer sq, String bilId) {
		this.pat = pat;
		this.sq = sq;
		this.bilId = bilId;
	}

	public String getBilId() {
		return bilId;
	}

	public void setBilId(String bilId) {
		this.bilId = bilId;
	}

	public String getPat() {
		return this.pat;
	}

	public void setPat(String pat) {
		this.pat = pat;
	}

	public Integer getSq() {
		return this.sq;
	}

	public void setSq(Integer sq) {
		this.sq = sq;
	}

}
