package com.ifbk.project.model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2014/4/22 下午 03:40:33 by Hibernate Tools 3.4.0.CR1

/**
 * Biln1 generated by hbm2java
 */
@Entity
@Table(name="CUR_ID")
public class CurId implements java.io.Serializable {

	@Id
	@Column(name="CUR_ID")
	private String curId;
	
	@Column(name="EXC_RTO")
	private BigDecimal excRto;

	public CurId() {
	}

	public CurId(String curId, BigDecimal excRto) {
		this.curId = curId;
		this.excRto = excRto;
	}

	public String getCurId() {
		return curId;
	}

	public void setCurId(String curId) {
		this.curId = curId;
	}

	public BigDecimal getExcRto() {
		return excRto;
	}

	public void setExcRto(BigDecimal excRto) {
		this.excRto = excRto;
	}


}
