package com.ifbk.project.model;

// Generated 2014/9/3 下午 03:44:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MfIj generated by hbm2java
 */
@Entity
@Table(name = "MF_IJ")
public class MfIj implements java.io.Serializable {
	
	@EmbeddedId
	private MfIjId id;
	@Column(name = "IJ_DD")
	private Date ijDd;
	@Column(name = "IJ_REASON")
	private String ijReason;
	@Column(name = "FIX_CST")
	private String fixCst;
	@Column(name = "ACC_NO_D")
	private String accNoD;
	@Column(name = "ACC_NO_C")
	private String accNoC;
	@Column(name = "DEP")
	private String dep;
	@Column(name = "VOH_ID")
	private String vohId;
	@Column(name = "VOH_NO")
	private String vohNo;
	@Column(name = "REF_NO")
	private String refNo;
	@Column(name = "BAT_NO")
	private String batNo;
	@Column(name = "MAN_NO")
	private String manNo;
	@Column(name = "REM")
	private String rem;
	@Column(name = "USR")
	private String usr;
	@Column(name = "CHK_MAN")
	private String chkMan;
	@Column(name = "PRT_SW")
	private String prtSw;
	@Column(name = "CPY_SW")
	private String cpySw;
	@Column(name = "BIL_NO")
	private String bilNo;
	@Column(name = "BIL_ID")
	private String bilId;
	@Column(name = "CLS_DATE")
	private Date clsDate;
	@Column(name = "POS_NO")
	private String posNo;
	@Column(name = "IJID")
	private BigDecimal ijid;
	@Column(name = "CAS_NO")
	private String casNo;
	@Column(name = "BIL_TYPE")
	private String bilType;
	@Column(name = "CNTT_NO")
	private String cnttNo;
	@Column(name = "ACC_NO_SS")
	private String accNoSs;
	@Column(name = "ACC_NO_SY")
	private String accNoSy;
	@Column(name = "MOB_ID")
	private String mobId;
	@Column(name = "LOCK_MAN")
	private String lockMan;
	@Column(name = "FJ_NUM")
	private Short fjNum;
	@Column(name = "SYS_DATE")
	private Date sysDate;
	@Column(name = "POS_ID")
	private String posId;
	@Column(name = "CUS_NO")
	private String cusNo;
	@Column(name = "TASK_ID")
	private Integer taskId;
	@Column(name = "PRT_USR")
	private String prtUsr;
	@Column(name = "SQ_ID")
	private String sqId;
	@Column(name = "SQ_NO")
	private String sqNo;
	@Column(name = "SQ_ITM")
	private Integer sqItm;
	@Column(name = "ISSVS")
	private String issvs;
	@Column(name = "FROMCB_CALC")
	private String fromcbCalc;
	@Column(name = "JH_SO_NO")
	private String jhSoNo;
	@Column(name = "TZZG")
	private String tzzg;

	public MfIj() {
	}

	public MfIj(MfIjId id) {
		this.id = id;
	}

	public MfIj(MfIjId id, Date ijDd, String ijReason, String fixCst,
			String accNoD, String accNoC, String dep, String vohId,
			String vohNo, String refNo, String batNo, String manNo, String rem,
			String usr, String chkMan, String prtSw, String cpySw,
			String bilNo, String bilId, Date clsDate, String posNo,
			BigDecimal ijid, String casNo, String bilType, String cnttNo,
			String accNoSs, String accNoSy, String mobId, String lockMan,
			Short fjNum, Date sysDate, String posId, String cusNo,
			Integer taskId, String prtUsr, String sqId, String sqNo,
			Integer sqItm, String issvs, String fromcbCalc, String jhSoNo,
			String tzzg) {
		this.id = id;
		this.ijDd = ijDd;
		this.ijReason = ijReason;
		this.fixCst = fixCst;
		this.accNoD = accNoD;
		this.accNoC = accNoC;
		this.dep = dep;
		this.vohId = vohId;
		this.vohNo = vohNo;
		this.refNo = refNo;
		this.batNo = batNo;
		this.manNo = manNo;
		this.rem = rem;
		this.usr = usr;
		this.chkMan = chkMan;
		this.prtSw = prtSw;
		this.cpySw = cpySw;
		this.bilNo = bilNo;
		this.bilId = bilId;
		this.clsDate = clsDate;
		this.posNo = posNo;
		this.ijid = ijid;
		this.casNo = casNo;
		this.bilType = bilType;
		this.cnttNo = cnttNo;
		this.accNoSs = accNoSs;
		this.accNoSy = accNoSy;
		this.mobId = mobId;
		this.lockMan = lockMan;
		this.fjNum = fjNum;
		this.sysDate = sysDate;
		this.posId = posId;
		this.cusNo = cusNo;
		this.taskId = taskId;
		this.prtUsr = prtUsr;
		this.sqId = sqId;
		this.sqNo = sqNo;
		this.sqItm = sqItm;
		this.issvs = issvs;
		this.fromcbCalc = fromcbCalc;
		this.jhSoNo = jhSoNo;
		this.tzzg = tzzg;
	}

	public MfIjId getId() {
		return this.id;
	}

	public void setId(MfIjId id) {
		this.id = id;
	}

	public Date getIjDd() {
		return this.ijDd;
	}

	public void setIjDd(Date ijDd) {
		this.ijDd = ijDd;
	}

	public String getIjReason() {
		return this.ijReason;
	}

	public void setIjReason(String ijReason) {
		this.ijReason = ijReason;
	}

	public String getFixCst() {
		return this.fixCst;
	}

	public void setFixCst(String fixCst) {
		this.fixCst = fixCst;
	}

	public String getAccNoD() {
		return this.accNoD;
	}

	public void setAccNoD(String accNoD) {
		this.accNoD = accNoD;
	}

	public String getAccNoC() {
		return this.accNoC;
	}

	public void setAccNoC(String accNoC) {
		this.accNoC = accNoC;
	}

	public String getDep() {
		return this.dep;
	}

	public void setDep(String dep) {
		this.dep = dep;
	}

	public String getVohId() {
		return this.vohId;
	}

	public void setVohId(String vohId) {
		this.vohId = vohId;
	}

	public String getVohNo() {
		return this.vohNo;
	}

	public void setVohNo(String vohNo) {
		this.vohNo = vohNo;
	}

	public String getRefNo() {
		return this.refNo;
	}

	public void setRefNo(String refNo) {
		this.refNo = refNo;
	}

	public String getBatNo() {
		return this.batNo;
	}

	public void setBatNo(String batNo) {
		this.batNo = batNo;
	}

	public String getManNo() {
		return this.manNo;
	}

	public void setManNo(String manNo) {
		this.manNo = manNo;
	}

	public String getRem() {
		return this.rem;
	}

	public void setRem(String rem) {
		this.rem = rem;
	}

	public String getUsr() {
		return this.usr;
	}

	public void setUsr(String usr) {
		this.usr = usr;
	}

	public String getChkMan() {
		return this.chkMan;
	}

	public void setChkMan(String chkMan) {
		this.chkMan = chkMan;
	}

	public String getPrtSw() {
		return this.prtSw;
	}

	public void setPrtSw(String prtSw) {
		this.prtSw = prtSw;
	}

	public String getCpySw() {
		return this.cpySw;
	}

	public void setCpySw(String cpySw) {
		this.cpySw = cpySw;
	}

	public String getBilNo() {
		return this.bilNo;
	}

	public void setBilNo(String bilNo) {
		this.bilNo = bilNo;
	}

	public String getBilId() {
		return this.bilId;
	}

	public void setBilId(String bilId) {
		this.bilId = bilId;
	}

	public Date getClsDate() {
		return this.clsDate;
	}

	public void setClsDate(Date clsDate) {
		this.clsDate = clsDate;
	}

	public String getPosNo() {
		return this.posNo;
	}

	public void setPosNo(String posNo) {
		this.posNo = posNo;
	}

	public BigDecimal getIjid() {
		return this.ijid;
	}

	public void setIjid(BigDecimal ijid) {
		this.ijid = ijid;
	}

	public String getCasNo() {
		return this.casNo;
	}

	public void setCasNo(String casNo) {
		this.casNo = casNo;
	}

	public String getBilType() {
		return this.bilType;
	}

	public void setBilType(String bilType) {
		this.bilType = bilType;
	}

	public String getCnttNo() {
		return this.cnttNo;
	}

	public void setCnttNo(String cnttNo) {
		this.cnttNo = cnttNo;
	}

	public String getAccNoSs() {
		return this.accNoSs;
	}

	public void setAccNoSs(String accNoSs) {
		this.accNoSs = accNoSs;
	}

	public String getAccNoSy() {
		return this.accNoSy;
	}

	public void setAccNoSy(String accNoSy) {
		this.accNoSy = accNoSy;
	}

	public String getMobId() {
		return this.mobId;
	}

	public void setMobId(String mobId) {
		this.mobId = mobId;
	}

	public String getLockMan() {
		return this.lockMan;
	}

	public void setLockMan(String lockMan) {
		this.lockMan = lockMan;
	}

	public Short getFjNum() {
		return this.fjNum;
	}

	public void setFjNum(Short fjNum) {
		this.fjNum = fjNum;
	}

	public Date getSysDate() {
		return this.sysDate;
	}

	public void setSysDate(Date sysDate) {
		this.sysDate = sysDate;
	}

	public String getPosId() {
		return this.posId;
	}

	public void setPosId(String posId) {
		this.posId = posId;
	}

	public String getCusNo() {
		return this.cusNo;
	}

	public void setCusNo(String cusNo) {
		this.cusNo = cusNo;
	}

	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public String getPrtUsr() {
		return this.prtUsr;
	}

	public void setPrtUsr(String prtUsr) {
		this.prtUsr = prtUsr;
	}

	public String getSqId() {
		return this.sqId;
	}

	public void setSqId(String sqId) {
		this.sqId = sqId;
	}

	public String getSqNo() {
		return this.sqNo;
	}

	public void setSqNo(String sqNo) {
		this.sqNo = sqNo;
	}

	public Integer getSqItm() {
		return this.sqItm;
	}

	public void setSqItm(Integer sqItm) {
		this.sqItm = sqItm;
	}

	public String getIssvs() {
		return this.issvs;
	}

	public void setIssvs(String issvs) {
		this.issvs = issvs;
	}

	public String getFromcbCalc() {
		return this.fromcbCalc;
	}

	public void setFromcbCalc(String fromcbCalc) {
		this.fromcbCalc = fromcbCalc;
	}

	public String getJhSoNo() {
		return this.jhSoNo;
	}

	public void setJhSoNo(String jhSoNo) {
		this.jhSoNo = jhSoNo;
	}

	public String getTzzg() {
		return this.tzzg;
	}

	public void setTzzg(String tzzg) {
		this.tzzg = tzzg;
	}

}
