package com.ifbk.project.model;

// Generated 2014/4/22 下午 03:40:33 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MfPos generated by hbm2java
 */
@Entity
@Table(name="MF_POS")
public class MfPos implements java.io.Serializable {

	@EmbeddedId
	private MfPosId id;
	
	@Column(name = "BAT_NO")
	private String batNo; 

	@Column(name = "OS_DD")
	@Temporal(TemporalType.DATE) 
	private Date osDd;

	@Column(name = "QT_NO")
	private String qtNo;
	
	@Column(name = "VOH_ID")
	private String vohId;
	
	@Column(name = "VOH_NO")
	private String vohNo;
	
	@Column(name = "TRAD_MTH")
	private String tradMth;
	
	@Column(name = "PAY_MTH")
	private String payMth;
	
	@Column(name = "PAY_DAYS")
	private Short payDays;
	
	@Column(name = "CHK_DAYS")
	private Short chkDays;
	
	@Column(name = "PAY_REM")
	private String payRem;
	
	@Column(name = "SEND_MTH")
	private String sendMth;
	
	@Column(name = "SEND_WH")
	private String sendWh;
	
	@Column(name = "EST_DD")
	@Temporal(TemporalType.DATE) 
	private Date estDd;
	
	@Column(name = "CUS_NO")
	private String cusNo;
	
	@Column(name = "SAL_NO")
	private String salNo;
	
	@Column(name = "USE_DEP")
	private String useDep;
	
	@Column(name = "CUR_ID")
	private String curId;
	
	@Column(name = "EXC_RTO")
	private BigDecimal excRto;
	
	@Column(name = "AMTN_INT")
	private BigDecimal amtnInt;
	
	@Column(name = "AMT_INT")
	private BigDecimal amtInt;

	@Column(name = "DIS_CNT")
	private BigDecimal disCnt;
	
	@Column(name = "CLS_ID")
	private String clsId;
	
	@Column(name = "BACK_ID")
	private String backId;
	
	@Column(name = "HIS_PRICE")
	private String hisPrice;
	
	@Column(name = "ADR")
	private String adr;
	
	@Column(name = "REM")
	private String rem;
	
	@Column(name = "PO_DEP")
	private String poDep;
	
	@Column(name = "PO_SO_NO")
	private String poSoNo;
	
	@Column(name = "SO_BY_MM")
	private Short soByMm;
	
	@Column(name = "SO_OT_DD")
	private Short soOtDd;
	
	@Column(name = "SO_BY_DD")
	private Short soByDd;
	
	@Column(name = "SO_LNG_CAS")
	private String soLngCas;
	
	@Column(name = "SO_END_DD")
	@Temporal(TemporalType.DATE) 
	private Date soEndDd;
	
	@Column(name = "SO_LST_DD")
	@Temporal(TemporalType.DATE) 
	private Date soLstDd;
	
	@Column(name = "INV_DIS_ID")
	private String invDisId;
	
	@Column(name = "INV_NO")
	private String invNo;
	
	@Column(name = "TAX_ID")
	private String taxId;
	
	@Column(name = "RP_NO")
	private String rpNo;
	
	@Column(name = "OLD_INV_NO")
	private String oldInvNo;
	
	@Column(name = "AMTN_NET")
	private BigDecimal amtnNet;
	
	@Column(name = "TAX")
	private BigDecimal tax;
	
	@Column(name = "PAY_DD")
	@Temporal(TemporalType.DATE) 
	private Date payDd;
	
	@Column(name = "CHK_DD")
	@Temporal(TemporalType.DATE) 
	private Date chkDd;
	
	@Column(name = "INT_DAYS")
	private Short intDays;
	
	@Column(name = "USR")
	private String usr;
	
	@Column(name = "CHK_MAN")
	private String chkMan;
	
	@Column(name = "CONTRACT")
	private String contract;
	
	@Column(name = "PRT_SW")
	private String prtSw;
	
	@Column(name = "CPY_SW")
	private String cpySw;
	
	@Column(name = "BIL_NO")
	private String bilNo;
	
	@Column(name = "LC_NO")
	private String lcNo;
	
	@Column(name = "AMTN_DIS")
	private BigDecimal amtnDis;
	
	@Column(name = "CLS_MP_ID")
	private String clsMpId;
	
	@Column(name = "CLS_REM")
	private String clsRem;
	
	@Column(name = "BIL_ID")
	private String bilId;
	
	@Column(name = "RK_CLS_ID")
	private String rkClsId;
	
	@Column(name = "PRE_ID")
	private String preId;
	
	@Column(name = "IS_POS")
	private String isPos;
	
	@Column(name = "POS_NO")
	private String posNo;
	
	@Column(name = "CLS_DATE")
	@Temporal(TemporalType.DATE) 
	private Date clsDate;
	
	@Column(name = "PCL_ID")
	private String pclId;
	
	@Column(name = "CUS_OS_NO")
	private String cusOsNo;
	
	@Column(name = "BZ_NO")
	private String bzNo;
	
	@Column(name = "HS_ID")
	private String hsId;
	
	@Column(name = "AMT_LC")
	private BigDecimal amtLc;
	
	@Column(name = "BIL_TYPE")
	private String bilType;
	
	@Column(name = "CNTT_NO")
	private String cnttNo;
	
	@Column(name = "SB_NO")
	private String sbNo;
	
	@Column(name = "MOB_ID")
	private String mobId;
	
	@Column(name = "LOCK_MAN")
	private String lockMan;
	
	@Column(name = "ISOVERSH")
	private String isoversh;
	
	@Column(name = "DJ_NO")
	private String djNo;
	
	@Column(name = "FJ_NUM")
	private Short fjNum;
	
	@Column(name = "CAS_NO")
	private String casNo;
	
	@Column(name = "SYS_DATE")
	@Temporal(TemporalType.DATE) 
	private Date sysDate;
	
	@Column(name = "SQ_ID")
	private String sqId;
	
	@Column(name = "INV_DD")
	@Temporal(TemporalType.DATE) 
	private Date invDd;
	
	@Column(name = "INV_YM")
	private Integer invYm;
	
	@Column(name = "TITLE_BUY")
	private String titleBuy;
	
	@Column(name = "METH_ID")
	private String methId;
	
	@Column(name = "AMT_INV")
	private BigDecimal amtInv;
	
	@Column(name = "TAX_INV")
	private BigDecimal taxInv;
	
	@Column(name = "QTY")
	private BigDecimal qty;
	
	@Column(name = "FX_WH")
	private String fxWh;
	
	@Column(name = "YH_NO")
	private String yhNo;
	
	@Column(name = "BYBOX")
	private String bybox;
	
	@Column(name = "TOT_QTY")
	private BigDecimal totQty;
	
	@Column(name = "TOT_BOX")
	private BigDecimal totBox;
	
	@Column(name = "TASK_ID")
	private Integer taskId;
	
	@Column(name = "PRT_USR")
	private String prtUsr;
	
	@Column(name = "RP_NO1")
	private String rpNo1;
	
	@Column(name = "SQ_NO")
	private String sqNo;
	
	@Column(name = "CARD_NO")
	private String cardNo;
	
	@Column(name = "SEND_AREA")
	private String sendArea;
	
	@Column(name = "JFEND_DD")
	@Temporal(TemporalType.DATE) 
	private Date jfendDd;
	
	@Column(name = "SG_ID")
	private String sgId;
	
	@Column(name = "PRT_NUM")
	private Integer prtNum;
	
	@Column(name = "PAY_NO")
	private String payNo;
	
	@Column(name = "ISSVS")
	private String issvs;
	
	@Column(name = "CHK_FX")
	private String chkFx;
	
	@Column(name = "HAS_FX")
	private String hasFx;
	
	@Column(name = "BIL_MARK")
	private String bilMark;
	
	@Column(name = "AMTN_YJBX")
	private BigDecimal amtnYjbx;
	
	@Column(name = "AMTN_BX")
	private BigDecimal amtnBx;
	
	@Column(name = "INV_CHK")
	private String invChk;
	
	@Column(name = "INV_UNI_NO")
	private String invUniNo;
	
	@Column(name = "INV_TITLE")
	private String invTitle;
	
	@Column(name = "INV_AMT")
	private BigDecimal invAmt;
	
	@Column(name = "PAY_B2C")
	private String payB2c;
	
	@Column(name = "AMTN_CBAC")
	private BigDecimal amtnCbac;
	
	@Column(name = "CBAC_CLS")
	private String cbacCls;
	
	@Column(name = "CFM_SW")
	private String cfmSw;
	
//	private Set tfPoses = new HashSet(0);

	public MfPos() {
	}

	public MfPos(MfPosId id) {
		this.id = id;
	}

	public MfPos (MfPosId id, String batNo, Date osDd, String qtNo,
			String vohId, String vohNo, String tradMth, String payMth,
			Short payDays, Short chkDays, String payRem, String sendMth,
			String sendWh, Date estDd, String cusNo, String salNo,
			String useDep, String curId, BigDecimal excRto, BigDecimal amtnInt,
			BigDecimal amtInt, BigDecimal disCnt, String clsId, String backId,
			String hisPrice, String adr, String rem, String poDep,
			String poSoNo, Short soByMm, Short soOtDd, Short soByDd,
			String soLngCas, Date soEndDd, Date soLstDd, String invDisId,
			String invNo, String taxId, String rpNo, String oldInvNo,
			BigDecimal amtnNet, BigDecimal tax, Date payDd, Date chkDd,
			Short intDays, String usr, String chkMan, String contract,
			String prtSw, String cpySw, String bilNo, String lcNo,
			BigDecimal amtnDis, String clsMpId, String clsRem, String bilId,
			String rkClsId, String preId, String isPos, String posNo,
			Date clsDate, String pclId, String cusOsNo, String bzNo,
			String hsId, BigDecimal amtLc, String bilType, String cnttNo,
			String sbNo, String mobId, String lockMan, String isoversh,
			String djNo, Short fjNum, String casNo, Date sysDate, String sqId,
			Date invDd, Integer invYm, String titleBuy, String methId,
			BigDecimal amtInv, BigDecimal taxInv, BigDecimal qty, String fxWh,
			String yhNo, String bybox, BigDecimal totQty, BigDecimal totBox,
			Integer taskId, String prtUsr, String rpNo1, String sqNo,
			String cardNo, String sendArea, Date jfendDd, String sgId,
			Integer prtNum, String payNo, String issvs, String chkFx,
			String hasFx, String bilMark, BigDecimal amtnYjbx,
			BigDecimal amtnBx, String invChk, String invUniNo, String invTitle,
			BigDecimal invAmt, String payB2c, BigDecimal amtnCbac,
			String cbacCls, String cfmSw
//			, Set tfPoses
			) {
		this.id = id;
		this.batNo = batNo;
		this.osDd = osDd;
		this.qtNo = qtNo;
		this.vohId = vohId;
		this.vohNo = vohNo;
		this.tradMth = tradMth;
		this.payMth = payMth;
		this.payDays = payDays;
		this.chkDays = chkDays;
		this.payRem = payRem;
		this.sendMth = sendMth;
		this.sendWh = sendWh;
		this.estDd = estDd;
		this.cusNo = cusNo;
		this.salNo = salNo;
		this.useDep = useDep;
		this.curId = curId;
		this.excRto = excRto;
		this.amtnInt = amtnInt;
		this.amtInt = amtInt;
		this.disCnt = disCnt;
		this.clsId = clsId;
		this.backId = backId;
		this.hisPrice = hisPrice;
		this.adr = adr;
		this.rem = rem;
		this.poDep = poDep;
		this.poSoNo = poSoNo;
		this.soByMm = soByMm;
		this.soOtDd = soOtDd;
		this.soByDd = soByDd;
		this.soLngCas = soLngCas;
		this.soEndDd = soEndDd;
		this.soLstDd = soLstDd;
		this.invDisId = invDisId;
		this.invNo = invNo;
		this.taxId = taxId;
		this.rpNo = rpNo;
		this.oldInvNo = oldInvNo;
		this.amtnNet = amtnNet;
		this.tax = tax;
		this.payDd = payDd;
		this.chkDd = chkDd;
		this.intDays = intDays;
		this.usr = usr;
		this.chkMan = chkMan;
		this.contract = contract;
		this.prtSw = prtSw;
		this.cpySw = cpySw;
		this.bilNo = bilNo;
		this.lcNo = lcNo;
		this.amtnDis = amtnDis;
		this.clsMpId = clsMpId;
		this.clsRem = clsRem;
		this.bilId = bilId;
		this.rkClsId = rkClsId;
		this.preId = preId;
		this.isPos = isPos;
		this.posNo = posNo;
		this.clsDate = clsDate;
		this.pclId = pclId;
		this.cusOsNo = cusOsNo;
		this.bzNo = bzNo;
		this.hsId = hsId;
		this.amtLc = amtLc;
		this.bilType = bilType;
		this.cnttNo = cnttNo;
		this.sbNo = sbNo;
		this.mobId = mobId;
		this.lockMan = lockMan;
		this.isoversh = isoversh;
		this.djNo = djNo;
		this.fjNum = fjNum;
		this.casNo = casNo;
		this.sysDate = sysDate;
		this.sqId = sqId;
		this.invDd = invDd;
		this.invYm = invYm;
		this.titleBuy = titleBuy;
		this.methId = methId;
		this.amtInv = amtInv;
		this.taxInv = taxInv;
		this.qty = qty;
		this.fxWh = fxWh;
		this.yhNo = yhNo;
		this.bybox = bybox;
		this.totQty = totQty;
		this.totBox = totBox;
		this.taskId = taskId;
		this.prtUsr = prtUsr;
		this.rpNo1 = rpNo1;
		this.sqNo = sqNo;
		this.cardNo = cardNo;
		this.sendArea = sendArea;
		this.jfendDd = jfendDd;
		this.sgId = sgId;
		this.prtNum = prtNum;
		this.payNo = payNo;
		this.issvs = issvs;
		this.chkFx = chkFx;
		this.hasFx = hasFx;
		this.bilMark = bilMark;
		this.amtnYjbx = amtnYjbx;
		this.amtnBx = amtnBx;
		this.invChk = invChk;
		this.invUniNo = invUniNo;
		this.invTitle = invTitle;
		this.invAmt = invAmt;
		this.payB2c = payB2c;
		this.amtnCbac = amtnCbac;
		this.cbacCls = cbacCls;
		this.cfmSw = cfmSw;
//		this.tfPoses = tfPoses;
	}

	public MfPosId getId() {
		return this.id;
	}

	public void setId(MfPosId id) {
		this.id = id;
	}

	public String getBatNo() {
		return this.batNo;
	}

	public void setBatNo(String batNo) {
		this.batNo = batNo;
	}

	public Date getOsDd() {
		return this.osDd;
	}

	public void setOsDd(Date osDd) {
		this.osDd = osDd;
	}

	public String getQtNo() {
		return this.qtNo;
	}

	public void setQtNo(String qtNo) {
		this.qtNo = qtNo;
	}

	public String getVohId() {
		return this.vohId;
	}

	public void setVohId(String vohId) {
		this.vohId = vohId;
	}

	public String getVohNo() {
		return this.vohNo;
	}

	public void setVohNo(String vohNo) {
		this.vohNo = vohNo;
	}

	public String getTradMth() {
		return this.tradMth;
	}

	public void setTradMth(String tradMth) {
		this.tradMth = tradMth;
	}

	public String getPayMth() {
		return this.payMth;
	}

	public void setPayMth(String payMth) {
		this.payMth = payMth;
	}

	public Short getPayDays() {
		return this.payDays;
	}

	public void setPayDays(Short payDays) {
		this.payDays = payDays;
	}

	public Short getChkDays() {
		return this.chkDays;
	}

	public void setChkDays(Short chkDays) {
		this.chkDays = chkDays;
	}

	public String getPayRem() {
		return this.payRem;
	}

	public void setPayRem(String payRem) {
		this.payRem = payRem;
	}

	public String getSendMth() {
		return this.sendMth;
	}

	public void setSendMth(String sendMth) {
		this.sendMth = sendMth;
	}

	public String getSendWh() {
		return this.sendWh;
	}

	public void setSendWh(String sendWh) {
		this.sendWh = sendWh;
	}

	public Date getEstDd() {
		return this.estDd;
	}

	public void setEstDd(Date estDd) {
		this.estDd = estDd;
	}

	public String getCusNo() {
		return this.cusNo;
	}

	public void setCusNo(String cusNo) {
		this.cusNo = cusNo;
	}

	public String getSalNo() {
		return this.salNo;
	}

	public void setSalNo(String salNo) {
		this.salNo = salNo;
	}

	public String getUseDep() {
		return this.useDep;
	}

	public void setUseDep(String useDep) {
		this.useDep = useDep;
	}

	public String getCurId() {
		return this.curId;
	}

	public void setCurId(String curId) {
		this.curId = curId;
	}

	public BigDecimal getExcRto() {
		return this.excRto;
	}

	public void setExcRto(BigDecimal excRto) {
		this.excRto = excRto;
	}

	public BigDecimal getAmtnInt() {
		return this.amtnInt;
	}

	public void setAmtnInt(BigDecimal amtnInt) {
		this.amtnInt = amtnInt;
	}

	public BigDecimal getAmtInt() {
		return this.amtInt;
	}

	public void setAmtInt(BigDecimal amtInt) {
		this.amtInt = amtInt;
	}

	public BigDecimal getDisCnt() {
		return this.disCnt;
	}

	public void setDisCnt(BigDecimal disCnt) {
		this.disCnt = disCnt;
	}

	public String getClsId() {
		return this.clsId;
	}

	public void setClsId(String clsId) {
		this.clsId = clsId;
	}

	public String getBackId() {
		return this.backId;
	}

	public void setBackId(String backId) {
		this.backId = backId;
	}

	public String getHisPrice() {
		return this.hisPrice;
	}

	public void setHisPrice(String hisPrice) {
		this.hisPrice = hisPrice;
	}

	public String getAdr() {
		return this.adr;
	}

	public void setAdr(String adr) {
		this.adr = adr;
	}

	public String getRem() {
		return this.rem;
	}

	public void setRem(String rem) {
		this.rem = rem;
	}

	public String getPoDep() {
		return this.poDep;
	}

	public void setPoDep(String poDep) {
		this.poDep = poDep;
	}

	public String getPoSoNo() {
		return this.poSoNo;
	}

	public void setPoSoNo(String poSoNo) {
		this.poSoNo = poSoNo;
	}

	public Short getSoByMm() {
		return this.soByMm;
	}

	public void setSoByMm(Short soByMm) {
		this.soByMm = soByMm;
	}

	public Short getSoOtDd() {
		return this.soOtDd;
	}

	public void setSoOtDd(Short soOtDd) {
		this.soOtDd = soOtDd;
	}

	public Short getSoByDd() {
		return this.soByDd;
	}

	public void setSoByDd(Short soByDd) {
		this.soByDd = soByDd;
	}

	public String getSoLngCas() {
		return this.soLngCas;
	}

	public void setSoLngCas(String soLngCas) {
		this.soLngCas = soLngCas;
	}

	public Date getSoEndDd() {
		return this.soEndDd;
	}

	public void setSoEndDd(Date soEndDd) {
		this.soEndDd = soEndDd;
	}

	public Date getSoLstDd() {
		return this.soLstDd;
	}

	public void setSoLstDd(Date soLstDd) {
		this.soLstDd = soLstDd;
	}

	public String getInvDisId() {
		return this.invDisId;
	}

	public void setInvDisId(String invDisId) {
		this.invDisId = invDisId;
	}

	public String getInvNo() {
		return this.invNo;
	}

	public void setInvNo(String invNo) {
		this.invNo = invNo;
	}

	public String getTaxId() {
		return this.taxId;
	}

	public void setTaxId(String taxId) {
		this.taxId = taxId;
	}

	public String getRpNo() {
		return this.rpNo;
	}

	public void setRpNo(String rpNo) {
		this.rpNo = rpNo;
	}

	public String getOldInvNo() {
		return this.oldInvNo;
	}

	public void setOldInvNo(String oldInvNo) {
		this.oldInvNo = oldInvNo;
	}

	public BigDecimal getAmtnNet() {
		return this.amtnNet;
	}

	public void setAmtnNet(BigDecimal amtnNet) {
		this.amtnNet = amtnNet;
	}

	public BigDecimal getTax() {
		return this.tax;
	}

	public void setTax(BigDecimal tax) {
		this.tax = tax;
	}

	public Date getPayDd() {
		return this.payDd;
	}

	public void setPayDd(Date payDd) {
		this.payDd = payDd;
	}

	public Date getChkDd() {
		return this.chkDd;
	}

	public void setChkDd(Date chkDd) {
		this.chkDd = chkDd;
	}

	public Short getIntDays() {
		return this.intDays;
	}

	public void setIntDays(Short intDays) {
		this.intDays = intDays;
	}

	public String getUsr() {
		return this.usr;
	}

	public void setUsr(String usr) {
		this.usr = usr;
	}

	public String getChkMan() {
		return this.chkMan;
	}

	public void setChkMan(String chkMan) {
		this.chkMan = chkMan;
	}

	public String getContract() {
		return this.contract;
	}

	public void setContract(String contract) {
		this.contract = contract;
	}

	public String getPrtSw() {
		return this.prtSw;
	}

	public void setPrtSw(String prtSw) {
		this.prtSw = prtSw;
	}

	public String getCpySw() {
		return this.cpySw;
	}

	public void setCpySw(String cpySw) {
		this.cpySw = cpySw;
	}

	public String getBilNo() {
		return this.bilNo;
	}

	public void setBilNo(String bilNo) {
		this.bilNo = bilNo;
	}

	public String getLcNo() {
		return this.lcNo;
	}

	public void setLcNo(String lcNo) {
		this.lcNo = lcNo;
	}

	public BigDecimal getAmtnDis() {
		return this.amtnDis;
	}

	public void setAmtnDis(BigDecimal amtnDis) {
		this.amtnDis = amtnDis;
	}

	public String getClsMpId() {
		return this.clsMpId;
	}

	public void setClsMpId(String clsMpId) {
		this.clsMpId = clsMpId;
	}

	public String getClsRem() {
		return this.clsRem;
	}

	public void setClsRem(String clsRem) {
		this.clsRem = clsRem;
	}

	public String getBilId() {
		return this.bilId;
	}

	public void setBilId(String bilId) {
		this.bilId = bilId;
	}

	public String getRkClsId() {
		return this.rkClsId;
	}

	public void setRkClsId(String rkClsId) {
		this.rkClsId = rkClsId;
	}

	public String getPreId() {
		return this.preId;
	}

	public void setPreId(String preId) {
		this.preId = preId;
	}

	public String getIsPos() {
		return this.isPos;
	}

	public void setIsPos(String isPos) {
		this.isPos = isPos;
	}

	public String getPosNo() {
		return this.posNo;
	}

	public void setPosNo(String posNo) {
		this.posNo = posNo;
	}

	public Date getClsDate() {
		return this.clsDate;
	}

	public void setClsDate(Date clsDate) {
		this.clsDate = clsDate;
	}

	public String getPclId() {
		return this.pclId;
	}

	public void setPclId(String pclId) {
		this.pclId = pclId;
	}

	public String getCusOsNo() {
		return this.cusOsNo;
	}

	public void setCusOsNo(String cusOsNo) {
		this.cusOsNo = cusOsNo;
	}

	public String getBzNo() {
		return this.bzNo;
	}

	public void setBzNo(String bzNo) {
		this.bzNo = bzNo;
	}

	public String getHsId() {
		return this.hsId;
	}

	public void setHsId(String hsId) {
		this.hsId = hsId;
	}

	public BigDecimal getAmtLc() {
		return this.amtLc;
	}

	public void setAmtLc(BigDecimal amtLc) {
		this.amtLc = amtLc;
	}

	public String getBilType() {
		return this.bilType;
	}

	public void setBilType(String bilType) {
		this.bilType = bilType;
	}

	public String getCnttNo() {
		return this.cnttNo;
	}

	public void setCnttNo(String cnttNo) {
		this.cnttNo = cnttNo;
	}

	public String getSbNo() {
		return this.sbNo;
	}

	public void setSbNo(String sbNo) {
		this.sbNo = sbNo;
	}

	public String getMobId() {
		return this.mobId;
	}

	public void setMobId(String mobId) {
		this.mobId = mobId;
	}

	public String getLockMan() {
		return this.lockMan;
	}

	public void setLockMan(String lockMan) {
		this.lockMan = lockMan;
	}

	public String getIsoversh() {
		return this.isoversh;
	}

	public void setIsoversh(String isoversh) {
		this.isoversh = isoversh;
	}

	public String getDjNo() {
		return this.djNo;
	}

	public void setDjNo(String djNo) {
		this.djNo = djNo;
	}

	public Short getFjNum() {
		return this.fjNum;
	}

	public void setFjNum(Short fjNum) {
		this.fjNum = fjNum;
	}

	public String getCasNo() {
		return this.casNo;
	}

	public void setCasNo(String casNo) {
		this.casNo = casNo;
	}

	public Date getSysDate() {
		return this.sysDate;
	}

	public void setSysDate(Date sysDate) {
		this.sysDate = sysDate;
	}

	public String getSqId() {
		return this.sqId;
	}

	public void setSqId(String sqId) {
		this.sqId = sqId;
	}

	public Date getInvDd() {
		return this.invDd;
	}

	public void setInvDd(Date invDd) {
		this.invDd = invDd;
	}

	public Integer getInvYm() {
		return this.invYm;
	}

	public void setInvYm(Integer invYm) {
		this.invYm = invYm;
	}

	public String getTitleBuy() {
		return this.titleBuy;
	}

	public void setTitleBuy(String titleBuy) {
		this.titleBuy = titleBuy;
	}

	public String getMethId() {
		return this.methId;
	}

	public void setMethId(String methId) {
		this.methId = methId;
	}

	public BigDecimal getAmtInv() {
		return this.amtInv;
	}

	public void setAmtInv(BigDecimal amtInv) {
		this.amtInv = amtInv;
	}

	public BigDecimal getTaxInv() {
		return this.taxInv;
	}

	public void setTaxInv(BigDecimal taxInv) {
		this.taxInv = taxInv;
	}

	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	public String getFxWh() {
		return this.fxWh;
	}

	public void setFxWh(String fxWh) {
		this.fxWh = fxWh;
	}

	public String getYhNo() {
		return this.yhNo;
	}

	public void setYhNo(String yhNo) {
		this.yhNo = yhNo;
	}

	public String getBybox() {
		return this.bybox;
	}

	public void setBybox(String bybox) {
		this.bybox = bybox;
	}

	public BigDecimal getTotQty() {
		return this.totQty;
	}

	public void setTotQty(BigDecimal totQty) {
		this.totQty = totQty;
	}

	public BigDecimal getTotBox() {
		return this.totBox;
	}

	public void setTotBox(BigDecimal totBox) {
		this.totBox = totBox;
	}

	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public String getPrtUsr() {
		return this.prtUsr;
	}

	public void setPrtUsr(String prtUsr) {
		this.prtUsr = prtUsr;
	}

	public String getRpNo1() {
		return this.rpNo1;
	}

	public void setRpNo1(String rpNo1) {
		this.rpNo1 = rpNo1;
	}

	public String getSqNo() {
		return this.sqNo;
	}

	public void setSqNo(String sqNo) {
		this.sqNo = sqNo;
	}

	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	public String getSendArea() {
		return this.sendArea;
	}

	public void setSendArea(String sendArea) {
		this.sendArea = sendArea;
	}

	public Date getJfendDd() {
		return this.jfendDd;
	}

	public void setJfendDd(Date jfendDd) {
		this.jfendDd = jfendDd;
	}

	public String getSgId() {
		return this.sgId;
	}

	public void setSgId(String sgId) {
		this.sgId = sgId;
	}

	public Integer getPrtNum() {
		return this.prtNum;
	}

	public void setPrtNum(Integer prtNum) {
		this.prtNum = prtNum;
	}

	public String getPayNo() {
		return this.payNo;
	}

	public void setPayNo(String payNo) {
		this.payNo = payNo;
	}

	public String getIssvs() {
		return this.issvs;
	}

	public void setIssvs(String issvs) {
		this.issvs = issvs;
	}

	public String getChkFx() {
		return this.chkFx;
	}

	public void setChkFx(String chkFx) {
		this.chkFx = chkFx;
	}

	public String getHasFx() {
		return this.hasFx;
	}

	public void setHasFx(String hasFx) {
		this.hasFx = hasFx;
	}

	public String getBilMark() {
		return this.bilMark;
	}

	public void setBilMark(String bilMark) {
		this.bilMark = bilMark;
	}

	public BigDecimal getAmtnYjbx() {
		return this.amtnYjbx;
	}

	public void setAmtnYjbx(BigDecimal amtnYjbx) {
		this.amtnYjbx = amtnYjbx;
	}

	public BigDecimal getAmtnBx() {
		return this.amtnBx;
	}

	public void setAmtnBx(BigDecimal amtnBx) {
		this.amtnBx = amtnBx;
	}

	public String getInvChk() {
		return this.invChk;
	}

	public void setInvChk(String invChk) {
		this.invChk = invChk;
	}

	public String getInvUniNo() {
		return this.invUniNo;
	}

	public void setInvUniNo(String invUniNo) {
		this.invUniNo = invUniNo;
	}

	public String getInvTitle() {
		return this.invTitle;
	}

	public void setInvTitle(String invTitle) {
		this.invTitle = invTitle;
	}

	public BigDecimal getInvAmt() {
		return this.invAmt;
	}

	public void setInvAmt(BigDecimal invAmt) {
		this.invAmt = invAmt;
	}

	public String getPayB2c() {
		return this.payB2c;
	}

	public void setPayB2c(String payB2c) {
		this.payB2c = payB2c;
	}

	public BigDecimal getAmtnCbac() {
		return this.amtnCbac;
	}

	public void setAmtnCbac(BigDecimal amtnCbac) {
		this.amtnCbac = amtnCbac;
	}

	public String getCbacCls() {
		return this.cbacCls;
	}

	public void setCbacCls(String cbacCls) {
		this.cbacCls = cbacCls;
	}

	public String getCfmSw() {
		return this.cfmSw;
	}

	public void setCfmSw(String cfmSw) {
		this.cfmSw = cfmSw;
	}

//	public Set getTfPoses() {
//		return this.tfPoses;
//	}
//
//	public void setTfPoses(Set tfPoses) {
//		this.tfPoses = tfPoses;
//	}

}
