package com.ifbk.project.model;

// Generated 2014/9/3 下午 03:44:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MyWh generated by hbm2java
 */
@Entity
@Table(name="MY_WH")
public class MyWh implements java.io.Serializable {

	/**
	 */
	private static final long serialVersionUID = -2803847812711402784L;

	@Id
	@Column(name = "WH")
	private String wh;
	public String getAttrib() {
		return attrib;
	}

	public void setAttrib(String attrib) {
		this.attrib = attrib;
	}

	public String getDep() {
		return dep;
	}

	public void setDep(String dep) {
		this.dep = dep;
	}

	public String getSpcId() {
		return spcId;
	}

	public void setSpcId(String spcId) {
		this.spcId = spcId;
	}

	@Column(name = "NAME")
	private String name;
	@Column(name = "ATTRIB")
	private String attrib;
	@Column(name = "DEP")
	private String dep;
//	@Column(name = "ADR")
//	private String adr;
//	@Column(name = "TEL_NO")
//	private String telNo;
//	@Column(name = "FAX_NO")
//	private String faxNo;
	@Column(name = "UP_WH")
	private String upWh;
	//	@Column(name = "CNT_MAN")
//	private String cntMan;
//	@Column(name = "INVALID")
//	private String invalid;
//	@Column(name = "STOP_DD")
//	private Date stopDd;
//	@Column(name = "CODE_NO")
//	private String codeNo;
	@Column(name = "CHK_WH")
	private String chkWh;
//	@Column(name = "REM")
//	private String rem;
//	@Column(name = "SENDCUS_NAME")
//	private String sendcusName;
//	@Column(name = "CON_MAN")
//	private String conMan;
//	@Column(name = "USR")
//	private String usr;
//	@Column(name = "SYS_DATE")
//	private Date sysDate;
//	@Column(name = "CUS_NO")
//	private String cusNo;
//	@Column(name = "ISLC")
//	private String islc;
	@Column(name = "SPC_ID")
	private String spcId;
//	@Column(name = "UP_DD")
//	private byte[] upDd;
//	@Column(name = "ISIOWH")
//	private String isiowh;

	public MyWh() {
	}

	public MyWh(String wh) {
		this.wh = wh;
	}

	public MyWh(String wh, String name, String upWh, String chkWh
//			, String attrib, String dep, String adr,
//			String telNo, String faxNo, String cntMan,
//			String invalid, Date stopDd, String codeNo,
//			String rem, String sendcusName, String conMan, String usr,
//			Date sysDate, String cusNo, String islc, String spcId, byte[] upDd,
//			String isiowh
			) {
		this.wh = wh;
		this.name = name;
//		this.attrib = attrib;
//		this.dep = dep;
//		this.adr = adr;
//		this.telNo = telNo;
//		this.faxNo = faxNo;
		this.upWh = upWh;
//		this.cntMan = cntMan;
//		this.invalid = invalid;
//		this.stopDd = stopDd;
//		this.codeNo = codeNo;
		this.chkWh = chkWh;
//		this.rem = rem;
//		this.sendcusName = sendcusName;
//		this.conMan = conMan;
//		this.usr = usr;
//		this.sysDate = sysDate;
//		this.cusNo = cusNo;
//		this.islc = islc;
//		this.spcId = spcId;
//		this.upDd = upDd;
//		this.isiowh = isiowh;
	}

	public String getChkWh() {
		return chkWh;
	}

	public void setChkWh(String chkWh) {
		this.chkWh = chkWh;
	}

	public String getUpWh() {
		return upWh;
	}

	public void setUpWh(String upWh) {
		this.upWh = upWh;
	}

	public String getWh() {
		return this.wh;
	}

	public void setWh(String wh) {
		this.wh = wh;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
//
//	public String getAttrib() {
//		return this.attrib;
//	}
//
//	public void setAttrib(String attrib) {
//		this.attrib = attrib;
//	}
//
//	public String getDep() {
//		return this.dep;
//	}
//
//	public void setDep(String dep) {
//		this.dep = dep;
//	}
//
//	public String getAdr() {
//		return this.adr;
//	}
//
//	public void setAdr(String adr) {
//		this.adr = adr;
//	}
//
//	public String getTelNo() {
//		return this.telNo;
//	}
//
//	public void setTelNo(String telNo) {
//		this.telNo = telNo;
//	}
//
//	public String getFaxNo() {
//		return this.faxNo;
//	}
//
//	public void setFaxNo(String faxNo) {
//		this.faxNo = faxNo;
//	}
//
//	public String getUpWh() {
//		return this.upWh;
//	}
//
//	public void setUpWh(String upWh) {
//		this.upWh = upWh;
//	}
//
//	public String getCntMan() {
//		return this.cntMan;
//	}
//
//	public void setCntMan(String cntMan) {
//		this.cntMan = cntMan;
//	}
//
//	public String getInvalid() {
//		return this.invalid;
//	}
//
//	public void setInvalid(String invalid) {
//		this.invalid = invalid;
//	}
//
//	public Date getStopDd() {
//		return this.stopDd;
//	}
//
//	public void setStopDd(Date stopDd) {
//		this.stopDd = stopDd;
//	}
//
//	public String getCodeNo() {
//		return this.codeNo;
//	}
//
//	public void setCodeNo(String codeNo) {
//		this.codeNo = codeNo;
//	}
//
//	public String getChkWh() {
//		return this.chkWh;
//	}
//
//	public void setChkWh(String chkWh) {
//		this.chkWh = chkWh;
//	}
//
//	public String getRem() {
//		return this.rem;
//	}
//
//	public void setRem(String rem) {
//		this.rem = rem;
//	}
//
//	public String getSendcusName() {
//		return this.sendcusName;
//	}
//
//	public void setSendcusName(String sendcusName) {
//		this.sendcusName = sendcusName;
//	}
//
//	public String getConMan() {
//		return this.conMan;
//	}
//
//	public void setConMan(String conMan) {
//		this.conMan = conMan;
//	}
//
//	public String getUsr() {
//		return this.usr;
//	}
//
//	public void setUsr(String usr) {
//		this.usr = usr;
//	}
//
//	public Date getSysDate() {
//		return this.sysDate;
//	}
//
//	public void setSysDate(Date sysDate) {
//		this.sysDate = sysDate;
//	}
//
//	public String getCusNo() {
//		return this.cusNo;
//	}
//
//	public void setCusNo(String cusNo) {
//		this.cusNo = cusNo;
//	}
//
//	public String getIslc() {
//		return this.islc;
//	}
//
//	public void setIslc(String islc) {
//		this.islc = islc;
//	}
//
//	public String getSpcId() {
//		return this.spcId;
//	}
//
//	public void setSpcId(String spcId) {
//		this.spcId = spcId;
//	}
//
//	public byte[] getUpDd() {
//		return this.upDd;
//	}
//
//	public void setUpDd(byte[] upDd) {
//		this.upDd = upDd;
//	}
//
//	public String getIsiowh() {
//		return this.isiowh;
//	}
//
//	public void setIsiowh(String isiowh) {
//		this.isiowh = isiowh;
//	}

}
