// default package
// Generated 2013/5/23 �W�� 11:36:16 by Hibernate Tools 3.3.0.GA
package com.ifbk.project.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pmt001 generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="POST")
public class NPost implements java.io.Serializable {
	@Id
	public String getPauth() {
		return pauth;
	}

	public void setPauth(String pauth) {
		this.pauth = pauth;
	}

	public String getPtitle() {
		return ptitle;
	}

	public void setPtitle(String ptitle) {
		this.ptitle = ptitle;
	}

	public String getPtime() {
		return ptime;
	}

	public void setPtime(String ptime) {
		this.ptime = ptime;
	}

	public String getPpush() {
		return ppush;
	}

	public void setPpush(String ppush) {
		this.ppush = ppush;
	}

	public String getPlink() {
		return plink;
	}

	public void setPlink(String plink) {
		this.plink = plink;
	}

	public String getPtag() {
		return ptag;
	}

	public void setPtag(String ptag) {
		this.ptag = ptag;
	}

	public String getPmonth() {
		return pmonth;
	}

	public void setPmonth(String pmonth) {
		this.pmonth = pmonth;
	}

	public String getPyear() {
		return pyear;
	}

	public void setPyear(String pyear) {
		this.pyear = pyear;
	}

	@Column(name = "PAUTH")
	private String pauth;
	
	@Column(name = "PTITLE")
	private String ptitle;
	
	@Column(name = "PTIME")
	private String ptime;
	
	@Column(name = "PPUSH")
	private String ppush;
	
	@Column(name = "PLINK")
	private String plink;

	@Column(name = "PTAG")
	private String ptag;
	
	@Column(name = "PMONTH")
	private String pmonth;
	
	@Column(name = "PYEAR")
	private String pyear;
	
	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "IP")
	private String ip;
	
	public NPost() {
	}
}
