package com.ifbk.project.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

// Generated 2014/9/3 下午 03:44:00 by Hibernate Tools 3.4.0.CR1

/**
 * PrdtCus1Id generated by hbm2java
 */
@Embeddable
public class PrdtCus1Id implements java.io.Serializable {

	@Column(name = "PRD_NO")
	private String prdNo;
	@Column(name = "AREA_NO")
	private String areaNo;
	@Column(name = "CUS_NO")
	private String cusNo;
	@Column(name = "SUP_PRD_NO")
	private String supPrdNo;
	@Column(name = "SUP_PRD_MARK")
	private String supPrdMark;
	@Column(name = "PRD_MARK")
	private String prdMark;

	public PrdtCus1Id() {
	}

	public PrdtCus1Id(String prdNo, String areaNo, String cusNo, String supPrdNo, String supPrdMark, String prdMark) {
		this.prdNo = prdNo;
		this.areaNo = areaNo;
		this.cusNo = cusNo;
		this.supPrdNo = supPrdNo;
		this.supPrdMark = supPrdMark;
		this.prdMark = prdMark;
	}

	public String getSupPrdMark() {
		return supPrdMark;
	}

	public void setSupPrdMark(String supPrdMark) {
		this.supPrdMark = supPrdMark;
	}

	public String getPrdMark() {
		return prdMark;
	}

	public void setPrdMark(String prdMark) {
		this.prdMark = prdMark;
	}

	public String getPrdNo() {
		return this.prdNo;
	}

	public void setPrdNo(String prdNo) {
		this.prdNo = prdNo;
	}

	public String getAreaNo() {
		return this.areaNo;
	}

	public void setAreaNo(String areaNo) {
		this.areaNo = areaNo;
	}

	public String getCusNo() {
		return this.cusNo;
	}

	public void setCusNo(String cusNo) {
		this.cusNo = cusNo;
	}

	public String getSupPrdNo() {
		return this.supPrdNo;
	}

	public void setSupPrdNo(String supPrdNo) {
		this.supPrdNo = supPrdNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrdtCus1Id))
			return false;
		PrdtCus1Id castOther = (PrdtCus1Id) other;

		return ((this.getPrdNo() == castOther.getPrdNo()) || (this.getPrdNo() != null
				&& castOther.getPrdNo() != null && this.getPrdNo().equals(
				castOther.getPrdNo())))
				&& ((this.getAreaNo() == castOther.getAreaNo()) || (this
						.getAreaNo() != null && castOther.getAreaNo() != null && this
						.getAreaNo().equals(castOther.getAreaNo())))
				&& ((this.getCusNo() == castOther.getCusNo()) || (this
						.getCusNo() != null && castOther.getCusNo() != null && this
						.getCusNo().equals(castOther.getCusNo())))
                && ((this.getSupPrdMark() == castOther.getSupPrdMark()) || (this
                        .getSupPrdMark() != null && castOther.getSupPrdMark() != null && this
                        .getSupPrdMark().equals(castOther.getSupPrdMark())))
                && ((this.getPrdMark() == castOther.getPrdMark()) || (this
                        .getPrdMark() != null && castOther.getPrdMark() != null && this
                        .getPrdMark().equals(castOther.getPrdMark())))
				&& ((this.getSupPrdNo() == castOther.getSupPrdNo()) || (this
						.getSupPrdNo() != null
						&& castOther.getSupPrdNo() != null && this
						.getSupPrdNo().equals(castOther.getSupPrdNo())));
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result
				+ (getPrdNo() == null ? 0 : this.getPrdNo().hashCode());
		result = 37 * result
				+ (getAreaNo() == null ? 0 : this.getAreaNo().hashCode());
		result = 37 * result
				+ (getCusNo() == null ? 0 : this.getCusNo().hashCode());
		result = 37 * result
				+ (getSupPrdNo() == null ? 0 : this.getSupPrdNo().hashCode());
		result = 37 * result
				+ (getSupPrdMark() == null ? 0 : this.getSupPrdMark().hashCode());
		result = 37 * result
				+ (getPrdMark() == null ? 0 : this.getPrdMark().hashCode());
		return result;
	}

}
