package com.ifbk.project.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

// Generated 2014/9/26 下午 05:06:34 by Hibernate Tools 3.4.0.CR1

/**
 * Prdt1Id generated by hbm2java
 */
@Embeddable
public class Prdt1Id implements java.io.Serializable {

	@Column(name = "WH")
	private String wh;
	@Column(name = "PRD_NO")
	private String prdNo;
	@Column(name = "PRD_MARK")
	private String prdMark;

	public Prdt1Id() {
	}

	public Prdt1Id(String wh, String prdNo, String prdMark) {
		this.wh = wh;
		this.prdNo = prdNo;
		this.prdMark = prdMark;
	}

	public String getWh() {
		return this.wh;
	}

	public void setWh(String wh) {
		this.wh = wh;
	}

	public String getPrdNo() {
		return this.prdNo;
	}

	public void setPrdNo(String prdNo) {
		this.prdNo = prdNo;
	}

	public String getPrdMark() {
		return this.prdMark;
	}

	public void setPrdMark(String prdMark) {
		this.prdMark = prdMark;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Prdt1Id))
			return false;
		Prdt1Id castOther = (Prdt1Id) other;

		return ((this.getWh() == castOther.getWh()) || (this.getWh() != null
				&& castOther.getWh() != null && this.getWh().equals(
				castOther.getWh())))
				&& ((this.getPrdNo() == castOther.getPrdNo()) || (this
						.getPrdNo() != null && castOther.getPrdNo() != null && this
						.getPrdNo().equals(castOther.getPrdNo())))
				&& ((this.getPrdMark() == castOther.getPrdMark()) || (this
						.getPrdMark() != null && castOther.getPrdMark() != null && this
						.getPrdMark().equals(castOther.getPrdMark())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getWh() == null ? 0 : this.getWh().hashCode());
		result = 37 * result
				+ (getPrdNo() == null ? 0 : this.getPrdNo().hashCode());
		result = 37 * result
				+ (getPrdMark() == null ? 0 : this.getPrdMark().hashCode());
		return result;
	}

}
