package com.ifbk.project.model;

// Generated 2014/9/3 下午 03:44:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PrdtCus1 generated by hbm2java
 */
@Entity
@Table(name = "PRDT_CUS1")
public class PrdtCus1 implements java.io.Serializable {

	/**
	 */
	private static final long serialVersionUID = 9087797543340587061L;

	@EmbeddedId
    private PrdtCus1Id id;
//	@Column(name = "SUP_PRD_NAME")
//	private String supPrdName;
//	@Column(name = "REM")
//	private String rem;
//	@Column(name = "LEN_CUS")
//	private BigDecimal lenCus;
//	@Column(name = "TYPE_CUS")
//	private String typeCus;
//	@Column(name = "REM_CUS")
//	private String remCus;
//	@Column(name = "UP")
//	private BigDecimal up;
//	@Column(name = "ZC_TYPE")
//	private String zcType;
//	@Column(name = "STOP_DD")
//	private Date stopDd;

	public PrdtCus1() {
	}

	public PrdtCus1(PrdtCus1Id id) {
		this.id = id;
	}

//	public PrdtCus1(PrdtCus1Id id, String supPrdName, String rem,
//			BigDecimal lenCus, String typeCus, String remCus, BigDecimal up,
//			String zcType, Date stopDd) {
//		this.id = id;
//		this.supPrdName = supPrdName;
//		this.rem = rem;
//		this.lenCus = lenCus;
//		this.typeCus = typeCus;
//		this.remCus = remCus;
//		this.up = up;
//		this.zcType = zcType;
//		this.stopDd = stopDd;
//	}

	public PrdtCus1Id getId() {
		return this.id;
	}

	public void setId(PrdtCus1Id id) {
		this.id = id;
	}
//
//	public String getSupPrdName() {
//		return this.supPrdName;
//	}
//
//	public void setSupPrdName(String supPrdName) {
//		this.supPrdName = supPrdName;
//	}
//
//	public String getRem() {
//		return this.rem;
//	}
//
//	public void setRem(String rem) {
//		this.rem = rem;
//	}
//
//	public BigDecimal getLenCus() {
//		return this.lenCus;
//	}
//
//	public void setLenCus(BigDecimal lenCus) {
//		this.lenCus = lenCus;
//	}
//
//	public String getTypeCus() {
//		return this.typeCus;
//	}
//
//	public void setTypeCus(String typeCus) {
//		this.typeCus = typeCus;
//	}
//
//	public String getRemCus() {
//		return this.remCus;
//	}
//
//	public void setRemCus(String remCus) {
//		this.remCus = remCus;
//	}
//
//	public BigDecimal getUp() {
//		return this.up;
//	}
//
//	public void setUp(BigDecimal up) {
//		this.up = up;
//	}
//
//	public String getZcType() {
//		return this.zcType;
//	}
//
//	public void setZcType(String zcType) {
//		this.zcType = zcType;
//	}
//
//	public Date getStopDd() {
//		return this.stopDd;
//	}
//
//	public void setStopDd(Date stopDd) {
//		this.stopDd = stopDd;
//	}

}
