package com.ifbk.project.model;

// Generated 2014/4/22 下午 03:40:33 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Prdt generated by hbm2java
 */
@Entity
@Table(name="PRDT")
public class Prdt implements java.io.Serializable {

	@Id
	@Column(name="PRD_NO")
	private String prdNo;
	
	@Column(name="WH")
	private String wh;

	@Column(name="NAME")
	private String name;
	@Column(name="SNM")
	private String snm;
	@Column(name="KND")
	private String knd;
	@Column(name="UT")
	private String ut;
	@Column(name="DFU_UT")
	private String dfuUt;
	@Column(name="CHK_TAX")
	private String chkTax;
	@Column(name="CHK_NUM")
	private String chkNum;
	@Column(name="CHK_BAT")
	private String chkBat;
	@Column(name="SPC_PRD")
	private String spcPrd;
	@Column(name="SPC_TAX")
	private BigDecimal spcTax;
	@Column(name="START_DD")
	private Date startDd;
	@Column(name="CHK_MAN")
	private String chkMan;
	@Column(name="CLS_DATE")
	private Date clsDate;
	@Column(name="USR")
	private String usr;
	@Column(name="SYS_DATE")
	private Date sysDate;
	@Column(name="ML_UT")
	private String mlUt;
	@Column(name="QUOTE_UT1")
	private String quoteUt1;
	@Column(name="QUOTE_UT2")
	private String quoteUt2;
	@Column(name="QUOTE_UT3")
	private String quoteUt3;

//	@Column(name="IDX1")
//	private String idx1;
//	@Column(name="IDX2")
//	private String idx2;
//	@Column(name="UT1")
//	private String ut1;
//	@Column(name="SPC")
//	private String spc;
//	@Column(name="CCC")
//	private String ccc;
//	@Column(name="PK2_UT")
//	private String pk2Ut;
//	@Column(name="PK2_QTY")
//	private BigDecimal pk2Qty;
//	@Column(name="PK3_UT")
//	private String pk3Ut;
//	@Column(name="PK3QTY")
//	private BigDecimal pk3Qty;
//	@Column(name="MRK")
//	private String mrk;
//	@Column(name="SUP1")
//	private String sup1;
//	@Column(name="SUP2")
//	private String sup2;
	@Column(name="UPR")
	private BigDecimal upr;
public BigDecimal getUpr() {
		return upr;
	}

	public void setUpr(BigDecimal upr) {
		this.upr = upr;
	}

	//	@Column(name="UBPR")
//	private Integer ubpr;
//	@Column(name="CST_STD")
//	private BigDecimal cstStd;
//	@Column(name="CST_SAL")
//	private BigDecimal cstSal;
//	@Column(name="REM")
//	private String rem;
//	@Column(name="PIC")
//	private byte[] pic;
//	@Column(name="UPR_LEVEL1")
//	private BigDecimal uprLevel1;
//	@Column(name="UPR_LEVEL2")
//	private BigDecimal uprLevel2;
//	@Column(name="UPR_LEVEL3")
//	private BigDecimal uprLevel3;
//	@Column(name="UPR_LEVEL4")
//	private BigDecimal uprLevel4;
	@Column(name="UPR_LEVEL5")
	private BigDecimal uprLevel5;
//	@Column(name="PAK_UNIT")
//	private String pakUnit;
//	@Column(name="PAK_EXC")
//	private BigDecimal pakExc;
//	@Column(name="PAK_NW")
//	private BigDecimal pakNw;
//	@Column(name="PAK_WEIGHT_UNIT")
//	private String pakWeightUnit;
//	@Column(name="PAK_GW")
//	private BigDecimal pakGw;
//	@Column(name="PAK_MEAST")
//	private BigDecimal pakMeast;
//	@Column(name="PAK_MEAST_UNIT")
//	private String pakMeastUnit;
//	@Column(name="STOP_ID")
//	private String stopId;
//	@Column(name="PRD_NO_EXC")
//	private String prdNoExc;
//	@Column(name="NEED_DAYS")
//	private BigDecimal needDays;
//	@Column(name="NOUSE_DD")
//	private Date nouseDd;
//	@Column(name="BAR_CODE")
//	private String barCode;
//	@Column(name="FORMULA")
//	private String formula;
//	@Column(name="NAME_ENG")
//	private String nameEng;
//	@Column(name="UT_TIME")
//	private BigDecimal utTime;
	
	
//	@Column(name="UP_MAX")
//	private BigDecimal upMax;
//	@Column(name="UP_MIN")
//	private BigDecimal upMin;
//	@Column(name="INV_NAME")
//	private String invName;
//	@Column(name="CST_ADD")
//	private BigDecimal cstAdd;
//	@Column(name="RB_RATE")
//	private BigDecimal rbRate;
//	@Column(name="QTY_LOW")
//	private BigDecimal qtyLow;
//	@Column(name="BOM_ID")
//	private String bomId;
//	@Column(name="TIME_UNIT")
//	private String timeUnit;
//	@Column(name="OLEFIELD")
//	private String olefield;
//	@Column(name="TW_ID")
//	private String twId;
//	@Column(name="WTUT")
//	private String wtut;
//	@Column(name="UP_SAL")
//	private BigDecimal upSal;
//	@Column(name="SMALLPIC")
//	private byte[] smallpic;
//	@Column(name="PRD_LEVEL")
//	private String prdLevel;
//	@Column(name="PRD_PACK")
//	private String prdPack;
//	@Column(name="ACC_NO_IN")
//	private String accNoIn;
//	@Column(name="ACC_NO_OUT")
//	private String accNoOut;
//	@Column(name="CODENAME")
//	private String codename;
//	@Column(name="UPR_TP")
//	private BigDecimal uprTp;
//	@Column(name="BACK_RTO")
//	private BigDecimal backRto;
//	@Column(name="DEP")
//	private String dep;
//	@Column(name="PRICEXS")
//	private BigDecimal pricexs;
//	@Column(name="TYPE_CST")
//	private String typeCst;
//	@Column(name="PRD_NO_SGT")
//	private String prdNoSgt;
//	@Column(name="HS_NO")
//	private String hsNo;
//	@Column(name="UNIT_SGT")
//	private String unitSgt;
//	@Column(name="SGT_RATE")
//	private BigDecimal sgtRate;
//	@Column(name="VAILD_DAYS")
//	private Short validDays;
//	@Column(name="NEED_DD")
//	private Short needDd;
//	@Column(name="MOB_ID")
//	private String mobId;
//	@Column(name="CHG_DAYS")
//	private Short chgDays;
//	@Column(name="ACC_NO_ORI")
//	private String accNoOri;
//	@Column(name="ACC_SA_IN")
//	private String accSaIn;
//	@Column(name="ACC_SA_CST")
//	private String accSaCst;
//	@Column(name="CHK_PRD_MARK")
//	private String chkPrdMark;
//	@Column(name="LEN_PRD")
//	private BigDecimal lenPrd;
//	@Column(name="UT_LEN")
//	private String utLen;
//	@Column(name="WIDTH_PRD")
//	private BigDecimal widthPrd;
//	@Column(name="UT_WIDTH")
//	private String utWidth;
//	@Column(name="LEN_PRD2")
//	private BigDecimal lenPrd2;
//	@Column(name="LEN_PRD3")
//	private BigDecimal lenPrd3;
//	@Column(name="CAIZ")
//	private String caiz;
//	@Column(name="SPC_ID")
//	private Short spcId;
//	@Column(name="ABC")
//	private String abc;
//	@Column(name="RTO_EP")
//	private BigDecimal rtoEp;
//	@Column(name="ZC_TYPE")
//	private String zcType;
//	@Column(name="JJ_LEN")
//	private BigDecimal jjLen;
//	@Column(name="JJ_LEN2")
//	private BigDecimal jjLen2;
//	@Column(name="NOT_RTN")
//	private String notRtn;
//	@Column(name="RTO_RTN")
//	private Short rtoRtn;
//	@Column(name="ACC_PRO_CST")
//	private String accProCst;
//	@Column(name="RTO_CL")
//	private BigDecimal rtoCl;
//	@Column(name="SAL_NO")
//	private String salNo;
//	@Column(name="OLD_CODE")
//	private String oldCode;
//	@Column(name="SPC_ID1")
//	private Short spcId1;
//	@Column(name="WH_LC")
//	private String whLc;
//	@Column(name="PRD_POI")
//	private Integer prdPoi;
//	@Column(name="QTY_MIN")
//	private BigDecimal qtyMin;
//	@Column(name="UP_DD")
//	private byte[] upDd;
//	@Column(name="DZ_DD")
//	private Date dzDd;
//	@Column(name="BZ_DATA")
//	private String bzData;
//	@Column(name="RTO_ID")
//	private String rtoId;
//	@Column(name="XN_NO")
//	private String xnNo;
//	@Column(name="CHK_MTN")
//	private String chkMtn;
//	@Column(name="CHK_INSTALL")
//	private String chkInstall;
//	@Column(name="MTN_LTIME")
//	private Integer mtnLtime;
//	@Column(name="CHK_RTN")
//	private String chkRtn;
//	@Column(name="STOP_PROD")
//	private String stopProd;
//	@Column(name="VIRTUAL_ID")
//	private String virtualId;
//	@Column(name="WEIGHT")
//	private BigDecimal weight;
//	@Column(name="REM_WEB")
//	private String remWeb;
//	@Column(name="B2C_HIDE")
//	private String b2cHide;
//	@Column(name="WEB_TITLE")
//	private String webTitle;
//	@Column(name="WEB_DESCRIPTION")
//	private String webDescription;
//	@Column(name="WEB_KEYWORDS")
//	private String webKeywords;
//	@Column(name="CADNAME")
//	private String cadname;
//	@Column(name="SA_RTO")
//	private BigDecimal saRto;

	public BigDecimal getUprLevel5() {
		return uprLevel5;
	}

	public void setUprLevel5(BigDecimal uprLevel5) {
		this.uprLevel5 = uprLevel5;
	}

	public Prdt() {
	}

	public Prdt(String prdNo) {
		this.prdNo = prdNo;
	}

//	public Prdt(String prdNo, String snm, String idx1, String idx2, String ut,
//			String ut1, String dfuUt, String name, String spc, String ccc,
//			String knd, BigDecimal spcTax, String pk2Ut, BigDecimal pk2Qty,
//			String pk3Ut, BigDecimal pk3Qty, String mrk, String sup1,
//			String sup2, BigDecimal upr, Integer ubpr, BigDecimal cstStd,
//			BigDecimal cstSal, String spcPrd, String rem, byte[] pic,
//			BigDecimal uprLevel1, BigDecimal uprLevel2, BigDecimal uprLevel3,
//			BigDecimal uprLevel4, BigDecimal uprLevel5, String pakUnit,
//			BigDecimal pakExc, BigDecimal pakNw, String pakWeightUnit,
//			BigDecimal pakGw, BigDecimal pakMeast, String pakMeastUnit,
//			String stopId, String prdNoExc, BigDecimal needDays, Date nouseDd,
//			String barCode, String formula, String nameEng, BigDecimal utTime,
//			String chkBat, BigDecimal upMax, BigDecimal upMin, String invName,
//			BigDecimal cstAdd, BigDecimal rbRate, BigDecimal qtyLow,
//			String bomId, String timeUnit, String wh, String olefield,
//			String twId, String wtut, BigDecimal upSal, String chkNum,
//			byte[] smallpic, String prdLevel, String prdPack, String accNoIn,
//			String accNoOut, String codename, String chkTax, BigDecimal uprTp,
//			BigDecimal backRto, String dep, BigDecimal pricexs, String typeCst,
//			String prdNoSgt, String hsNo, String unitSgt, BigDecimal sgtRate,
//			Short validDays, Short needDd, String mobId, Date startDd,
//			Short chgDays, String accNoOri, String accSaIn, String accSaCst,
//			String chkPrdMark, String chkMan, Date clsDate, BigDecimal lenPrd,
//			String utLen, BigDecimal widthPrd, String utWidth,
//			BigDecimal lenPrd2, BigDecimal lenPrd3, String caiz, String usr,
//			Date sysDate, Short spcId, String abc, BigDecimal rtoEp,
//			String zcType, BigDecimal jjLen, BigDecimal jjLen2, String notRtn,
//			Short rtoRtn, String accProCst, BigDecimal rtoCl, String salNo,
//			String oldCode, Short spcId1, String mlUt, String whLc,
//			String quoteUt1, String quoteUt2, String quoteUt3, Integer prdPoi,
//			BigDecimal qtyMin, byte[] upDd, Date dzDd, String bzData,
//			String rtoId, String xnNo, String chkMtn, String chkInstall,
//			Integer mtnLtime, String chkRtn, String stopProd, String virtualId,
//			BigDecimal weight, String remWeb, String b2cHide, String webTitle,
//			String webDescription, String webKeywords, String cadname,
//			BigDecimal saRto) {
//		this.prdNo = prdNo;
//		this.snm = snm;
//		this.idx1 = idx1;
//		this.idx2 = idx2;
//		this.ut = ut;
//		this.ut1 = ut1;
//		this.dfuUt = dfuUt;
//		this.name = name;
//		this.spc = spc;
//		this.ccc = ccc;
//		this.knd = knd;
//		this.spcTax = spcTax;
//		this.pk2Ut = pk2Ut;
//		this.pk2Qty = pk2Qty;
//		this.pk3Ut = pk3Ut;
//		this.pk3Qty = pk3Qty;
//		this.mrk = mrk;
//		this.sup1 = sup1;
//		this.sup2 = sup2;
//		this.upr = upr;
//		this.ubpr = ubpr;
//		this.cstStd = cstStd;
//		this.cstSal = cstSal;
//		this.spcPrd = spcPrd;
//		this.rem = rem;
//		this.pic = pic;
//		this.uprLevel1 = uprLevel1;
//		this.uprLevel2 = uprLevel2;
//		this.uprLevel3 = uprLevel3;
//		this.uprLevel4 = uprLevel4;
//		this.uprLevel5 = uprLevel5;
//		this.pakUnit = pakUnit;
//		this.pakExc = pakExc;
//		this.pakNw = pakNw;
//		this.pakWeightUnit = pakWeightUnit;
//		this.pakGw = pakGw;
//		this.pakMeast = pakMeast;
//		this.pakMeastUnit = pakMeastUnit;
//		this.stopId = stopId;
//		this.prdNoExc = prdNoExc;
//		this.needDays = needDays;
//		this.nouseDd = nouseDd;
//		this.barCode = barCode;
//		this.formula = formula;
//		this.nameEng = nameEng;
//		this.utTime = utTime;
//		this.chkBat = chkBat;
//		this.upMax = upMax;
//		this.upMin = upMin;
//		this.invName = invName;
//		this.cstAdd = cstAdd;
//		this.rbRate = rbRate;
//		this.qtyLow = qtyLow;
//		this.bomId = bomId;
//		this.timeUnit = timeUnit;
//		this.wh = wh;
//		this.olefield = olefield;
//		this.twId = twId;
//		this.wtut = wtut;
//		this.upSal = upSal;
//		this.chkNum = chkNum;
//		this.smallpic = smallpic;
//		this.prdLevel = prdLevel;
//		this.prdPack = prdPack;
//		this.accNoIn = accNoIn;
//		this.accNoOut = accNoOut;
//		this.codename = codename;
//		this.chkTax = chkTax;
//		this.uprTp = uprTp;
//		this.backRto = backRto;
//		this.dep = dep;
//		this.pricexs = pricexs;
//		this.typeCst = typeCst;
//		this.prdNoSgt = prdNoSgt;
//		this.hsNo = hsNo;
//		this.unitSgt = unitSgt;
//		this.sgtRate = sgtRate;
//		this.validDays = validDays;
//		this.needDd = needDd;
//		this.mobId = mobId;
//		this.startDd = startDd;
//		this.chgDays = chgDays;
//		this.accNoOri = accNoOri;
//		this.accSaIn = accSaIn;
//		this.accSaCst = accSaCst;
//		this.chkPrdMark = chkPrdMark;
//		this.chkMan = chkMan;
//		this.clsDate = clsDate;
//		this.lenPrd = lenPrd;
//		this.utLen = utLen;
//		this.widthPrd = widthPrd;
//		this.utWidth = utWidth;
//		this.lenPrd2 = lenPrd2;
//		this.lenPrd3 = lenPrd3;
//		this.caiz = caiz;
//		this.usr = usr;
//		this.sysDate = sysDate;
//		this.spcId = spcId;
//		this.abc = abc;
//		this.rtoEp = rtoEp;
//		this.zcType = zcType;
//		this.jjLen = jjLen;
//		this.jjLen2 = jjLen2;
//		this.notRtn = notRtn;
//		this.rtoRtn = rtoRtn;
//		this.accProCst = accProCst;
//		this.rtoCl = rtoCl;
//		this.salNo = salNo;
//		this.oldCode = oldCode;
//		this.spcId1 = spcId1;
//		this.mlUt = mlUt;
//		this.whLc = whLc;
//		this.quoteUt1 = quoteUt1;
//		this.quoteUt2 = quoteUt2;
//		this.quoteUt3 = quoteUt3;
//		this.prdPoi = prdPoi;
//		this.qtyMin = qtyMin;
//		this.upDd = upDd;
//		this.dzDd = dzDd;
//		this.bzData = bzData;
//		this.rtoId = rtoId;
//		this.xnNo = xnNo;
//		this.chkMtn = chkMtn;
//		this.chkInstall = chkInstall;
//		this.mtnLtime = mtnLtime;
//		this.chkRtn = chkRtn;
//		this.stopProd = stopProd;
//		this.virtualId = virtualId;
//		this.weight = weight;
//		this.remWeb = remWeb;
//		this.b2cHide = b2cHide;
//		this.webTitle = webTitle;
//		this.webDescription = webDescription;
//		this.webKeywords = webKeywords;
//		this.cadname = cadname;
//		this.saRto = saRto;
//	}

	public String getPrdNo() {
		return this.prdNo;
	}

	public void setPrdNo(String prdNo) {
		this.prdNo = prdNo;
	}

	public String getWh() {
		return this.wh;
	}

	public void setWh(String wh) {
		this.wh = wh;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSnm() {
		return snm;
	}

	public void setSnm(String snm) {
		this.snm = snm;
	}

	public String getKnd() {
		return knd;
	}

	public void setKnd(String knd) {
		this.knd = knd;
	}

	public String getUt() {
		return ut;
	}

	public void setUt(String ut) {
		this.ut = ut;
	}

	public String getDfuUt() {
		return dfuUt;
	}

	public void setDfuUt(String dfuUt) {
		this.dfuUt = dfuUt;
	}

	public String getChkTax() {
		return chkTax;
	}

	public void setChkTax(String chkTax) {
		this.chkTax = chkTax;
	}

	public String getChkNum() {
		return chkNum;
	}

	public void setChkNum(String chkNum) {
		this.chkNum = chkNum;
	}

	public String getChkBat() {
		return chkBat;
	}

	public void setChkBat(String chkBat) {
		this.chkBat = chkBat;
	}

	public String getSpcPrd() {
		return spcPrd;
	}

	public void setSpcPrd(String spcPrd) {
		this.spcPrd = spcPrd;
	}

	public BigDecimal getSpcTax() {
		return spcTax;
	}

	public void setSpcTax(BigDecimal spcTax) {
		this.spcTax = spcTax;
	}

	public Date getStartDd() {
		return startDd;
	}

	public void setStartDd(Date startDd) {
		this.startDd = startDd;
	}

	public String getChkMan() {
		return chkMan;
	}

	public void setChkMan(String chkMan) {
		this.chkMan = chkMan;
	}

	public Date getClsDate() {
		return clsDate;
	}

	public void setClsDate(Date clsDate) {
		this.clsDate = clsDate;
	}

	public String getUsr() {
		return usr;
	}

	public void setUsr(String usr) {
		this.usr = usr;
	}

	public Date getSysDate() {
		return sysDate;
	}

	public void setSysDate(Date sysDate) {
		this.sysDate = sysDate;
	}

	public String getMlUt() {
		return mlUt;
	}

	public void setMlUt(String mlUt) {
		this.mlUt = mlUt;
	}

	public String getQuoteUt1() {
		return quoteUt1;
	}

	public void setQuoteUt1(String quoteUt1) {
		this.quoteUt1 = quoteUt1;
	}

	public String getQuoteUt2() {
		return quoteUt2;
	}

	public void setQuoteUt2(String quoteUt2) {
		this.quoteUt2 = quoteUt2;
	}

	public String getQuoteUt3() {
		return quoteUt3;
	}

	public void setQuoteUt3(String quoteUt3) {
		this.quoteUt3 = quoteUt3;
	}

}
