package com.ifbk.project.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

// Generated 2014/10/1 下午 02:42:57 by Hibernate Tools 3.4.0.CR1

/**
 * PrdtUtId generated by hbm2java
 */
@Embeddable
public class PrdtUtId implements java.io.Serializable {

	@Column(name = "UT_ID")
	private String utId;
	@Column(name = "UT")
	private String ut;

	public PrdtUtId() {
	}

	public PrdtUtId(String utId, String ut) {
		this.utId = utId;
		this.ut = ut;
	}

	public String getUtId() {
		return this.utId;
	}

	public void setUtId(String utId) {
		this.utId = utId;
	}

	public String getUt() {
		return this.ut;
	}

	public void setUt(String ut) {
		this.ut = ut;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrdtUtId))
			return false;
		PrdtUtId castOther = (PrdtUtId) other;

		return ((this.getUtId() == castOther.getUtId()) || (this.getUtId() != null
				&& castOther.getUtId() != null && this.getUtId().equals(
				castOther.getUtId())))
				&& ((this.getUt() == castOther.getUt()) || (this.getUt() != null
						&& castOther.getUt() != null && this.getUt().equals(
						castOther.getUt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUtId() == null ? 0 : this.getUtId().hashCode());
		result = 37 * result + (getUt() == null ? 0 : this.getUt().hashCode());
		return result;
	}

}
