package com.ifbk.project.model;
//package com.ifbk.project.model;
//
//// Generated 2014/5/6 下午 03:37:37 by Hibernate Tools 3.4.0.CR1
//
//import java.math.BigDecimal;
//import java.util.Date;
//
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.Id;
//import javax.persistence.Table;
//
///**
// * Prdt generated by hbm2java
// */
//@Entity
//@Table(name = "PRDT_CUS1")
//public class PrdtCus1 implements java.io.Serializable {
//
//	@Id
//	@Column(name = "PRD_NO")
//	private String prdNo;
//
//	@Column(name = "CUS_NO")
//	private String cusNo;
//	
//	@Column(name = "SUP_PRD_NO")
//	private String supPrdNo;
//	
//	@Column(name = "AREA_NO")
//	private String areaNo;
//
//	public PrdtCus1() {
//	}
//
//	public String getAreaNo() {
//		return areaNo;
//	}
//
//	public void setAreaNo(String areaNo) {
//		this.areaNo = areaNo;
//	}
//
//	public PrdtCus1(String prdNo) {
//		this.prdNo = prdNo;
//	}
//
//	public PrdtCus1(String prdNo, String cusNo, String supPrdNo, String areaNo) {
//		this.prdNo = prdNo;
//		this.cusNo = cusNo;
//		this.supPrdNo = supPrdNo;
//		this.areaNo = areaNo;
//	}
//
//	public String getPrdNo() {
//		return prdNo;
//	}
//
//	public void setPrdNo(String prdNo) {
//		this.prdNo = prdNo;
//	}
//
//	public String getCusNo() {
//		return cusNo;
//	}
//
//	public void setCusNo(String cusNo) {
//		this.cusNo = cusNo;
//	}
//
//	public String getSupPrdNo() {
//		return supPrdNo;
//	}
//
//	public void setSupPrdNo(String supPrdNo) {
//		this.supPrdNo = supPrdNo;
//	}
//
//	
//}
