package com.ifbk.project.model;

import javax.persistence.Column;

// Generated 2014/9/3 下午 03:44:00 by Hibernate Tools 3.4.0.CR1

/**
 * TfIjId generated by hbm2java
 */
public class TfIjId implements java.io.Serializable {

	@Column(name = "IJ_ID")
	private String ijId;
	@Column(name = "IJ_NO")
	private String ijNo;
	private int itm;

	public TfIjId() {
	}

	public TfIjId(String ijId, String ijNo, int itm) {
		this.ijId = ijId;
		this.ijNo = ijNo;
		this.itm = itm;
	}

	public String getIjId() {
		return this.ijId;
	}

	public void setIjId(String ijId) {
		this.ijId = ijId;
	}

	public String getIjNo() {
		return this.ijNo;
	}

	public void setIjNo(String ijNo) {
		this.ijNo = ijNo;
	}

	public int getItm() {
		return this.itm;
	}

	public void setItm(int itm) {
		this.itm = itm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TfIjId))
			return false;
		TfIjId castOther = (TfIjId) other;

		return ((this.getIjId() == castOther.getIjId()) || (this.getIjId() != null
				&& castOther.getIjId() != null && this.getIjId().equals(
				castOther.getIjId())))
				&& ((this.getIjNo() == castOther.getIjNo()) || (this.getIjNo() != null
						&& castOther.getIjNo() != null && this.getIjNo()
						.equals(castOther.getIjNo())))
				&& (this.getItm() == castOther.getItm());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIjId() == null ? 0 : this.getIjId().hashCode());
		result = 37 * result
				+ (getIjNo() == null ? 0 : this.getIjNo().hashCode());
		result = 37 * result + this.getItm();
		return result;
	}

}
