package com.ifbk.project.model;

// Generated 2014/9/3 下午 03:44:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TfIj generated by hbm2java
 */
@Entity
@Table(name = "TF_IJ")
public class TfIj implements java.io.Serializable {

	
	@EmbeddedId
	private TfIjId id;
	
	@Column(name = "WH")
	private String wh;
	@Column(name = "UNIT")
	private String unit;
	@Column(name = "QTY")
	private BigDecimal qty;
	@Column(name = "CST")
	private BigDecimal cst;
	@Column(name = "IJ_DD")
	private Date ijDd;
	@Column(name = "PRE_ITM")
	private Integer preItm;
	@Column(name = "KEY_ITM")
	private Integer keyItm;

	@Column(name = "PRD_NO")
	private String prdNo;
//	@Column(name = "PRD_MARK")
//	private String prdMark;
//	@Column(name = "QTY1")
//	private BigDecimal qty1;
//	@Column(name = "IN_PRICE")
//	private BigDecimal inPrice;
	@Column(name = "FIX_CST")
	private String fixCst;
//	@Column(name = "BAT_NO")
//	private String batNo;
//	@Column(name = "REM")
//	private String rem;
//	@Column(name = "CST_STD")
//	private BigDecimal cstStd;
//	@Column(name = "ID_NO")
//	private String idNo;
//	@Column(name = "IJID")
//	private BigDecimal ijid;
//	@Column(name = "CNTT_NO")
//	private String cnttNo;
//	@Column(name = "COMPOST_IDNO")
//	private String composeIdno;
//	@Column(name = "BIL_ID")
//	private String bilId;
//	@Column(name = "BIL_NO")
//	private String bilNo;
//	@Column(name = "EST_ITM")
//	private Integer estItm;
//	@Column(name = "SPC_NO")
//	private String spcNo;
//	@Column(name = "SUP_PRD_NO")
//	private String supPrdNo;
//	@Column(name = "BOX_ITM")
//	private Integer boxItm;
//	@Column(name = "UP")
//	private BigDecimal up;
//	@Column(name = "VALID_DD")
//	private Date validDd;
//	@Column(name = "RK_DD")
//	private Date rkDd;
//	@Column(name = "AMTN")
//	private BigDecimal amtn;
//	@Column(name = "SQ_ID")
//	private String sqId;
//	@Column(name = "SQ_NO")
//	private String sqNo;
//	@Column(name = "SQ_ITM")
//	private Integer sqItm;
//	@Column(name = "DEP_RK")
//	private String depRk;
//	@Column(name = "PW_ITM")
//	private Integer pwItm;
//	@Column(name = "PRD_NO_SO_RES")
//	private String prdNoSoRes;
//	@Column(name = "PAK_UNIT")
//	private String pakUnit;
//	@Column(name = "PAK_EXC")
//	private BigDecimal pakExc;
//	@Column(name = "PAK_NW_N")
//	private BigDecimal pakNwN;
//	@Column(name = "PAK_NW")
//	private BigDecimal pakNw;
//	@Column(name = "PAK_WEIGHT_UNIT")
//	private String pakWeightUnit;
//	@Column(name = "PAK_GW_N")
//	private BigDecimal pakGwN;
//	@Column(name = "PAK_GW")
//	private BigDecimal pakGw;
//	@Column(name = "PAK_MEAST")
//	private BigDecimal pakMeast;
//	@Column(name = "PAK_MEAST_UNIT")
//	private String pakMeastUnit;

	public TfIj() {
	}

	public TfIj(TfIjId id) {
		this.id = id;
	}

	public TfIj(TfIjId id, Date ijDd, String wh, String unit, BigDecimal qty, BigDecimal cst
			, Integer keyItm, Integer preItm, String prdNo, String fixCst
//			, String prdNo, String prdMark
//			, BigDecimal qty1,
//			BigDecimal inPrice, String fixCst, String batNo, String rem,
//			BigDecimal cstStd, String idNo, BigDecimal ijid, String cnttNo,
//			String composeIdno, String bilId, String bilNo,
//			Integer estItm, String spcNo, String supPrdNo, 
//			Integer boxItm, BigDecimal up, Date validDd, Date rkDd,
//			BigDecimal amtn, String sqId, String sqNo, Integer sqItm,
//			String depRk, Integer pwItm, String prdNoSoRes, String pakUnit,
//			BigDecimal pakExc, BigDecimal pakNwN, BigDecimal pakNw,
//			String pakWeightUnit, BigDecimal pakGwN, BigDecimal pakGw,
//			BigDecimal pakMeast, String pakMeastUnit
			) {
		this.id = id;
		this.ijDd = ijDd;
		this.wh = wh;
		this.unit = unit;
		this.qty = qty;
		this.cst = cst;
		this.preItm = preItm;
		this.keyItm = keyItm;
		this.prdNo = prdNo;
//		this.prdMark = prdMark;
//		this.qty1 = qty1;
//		this.inPrice = inPrice;
		this.fixCst = fixCst;
//		this.batNo = batNo;
//		this.rem = rem;
//		this.cstStd = cstStd;
//		this.idNo = idNo;
//		this.ijid = ijid;
//		this.cnttNo = cnttNo;
//		this.composeIdno = composeIdno;
//		this.bilId = bilId;
//		this.bilNo = bilNo;
//		this.estItm = estItm;
//		this.spcNo = spcNo;
//		this.supPrdNo = supPrdNo;
//		this.boxItm = boxItm;
//		this.up = up;
//		this.validDd = validDd;
//		this.rkDd = rkDd;
//		this.amtn = amtn;
//		this.sqId = sqId;
//		this.sqNo = sqNo;
//		this.sqItm = sqItm;
//		this.depRk = depRk;
//		this.pwItm = pwItm;
//		this.prdNoSoRes = prdNoSoRes;
//		this.pakUnit = pakUnit;
//		this.pakExc = pakExc;
//		this.pakNwN = pakNwN;
//		this.pakNw = pakNw;
//		this.pakWeightUnit = pakWeightUnit;
//		this.pakGwN = pakGwN;
//		this.pakGw = pakGw;
//		this.pakMeast = pakMeast;
//		this.pakMeastUnit = pakMeastUnit;
	}

	public TfIjId getId() {
		return this.id;
	}

	public void setId(TfIjId id) {
		this.id = id;
	}

	public Date getIjDd() {
		return this.ijDd;
	}

	public void setIjDd(Date ijDd) {
		this.ijDd = ijDd;
	}

	public String getPrdNo() {
		return this.prdNo;
	}

	public void setPrdNo(String prdNo) {
		this.prdNo = prdNo;
	}
//
//	public String getPrdMark() {
//		return this.prdMark;
//	}
//
//	public void setPrdMark(String prdMark) {
//		this.prdMark = prdMark;
//	}

	public String getWh() {
		return this.wh;
	}

	public void setWh(String wh) {
		this.wh = wh;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

//	public BigDecimal getQty1() {
//		return this.qty1;
//	}
//
//	public void setQty1(BigDecimal qty1) {
//		this.qty1 = qty1;
//	}

	public BigDecimal getCst() {
		return this.cst;
	}

	public void setCst(BigDecimal cst) {
		this.cst = cst;
	}

//	public BigDecimal getInPrice() {
//		return this.inPrice;
//	}
//
//	public void setInPrice(BigDecimal inPrice) {
//		this.inPrice = inPrice;
//	}
//
	public String getFixCst() {
		return this.fixCst;
	}

	public void setFixCst(String fixCst) {
		this.fixCst = fixCst;
	}
//
//	public String getBatNo() {
//		return this.batNo;
//	}
//
//	public void setBatNo(String batNo) {
//		this.batNo = batNo;
//	}
//
//	public String getRem() {
//		return this.rem;
//	}
//
//	public void setRem(String rem) {
//		this.rem = rem;
//	}
//
//	public BigDecimal getCstStd() {
//		return this.cstStd;
//	}
//
//	public void setCstStd(BigDecimal cstStd) {
//		this.cstStd = cstStd;
//	}
//
//	public String getIdNo() {
//		return this.idNo;
//	}
//
//	public void setIdNo(String idNo) {
//		this.idNo = idNo;
//	}
//
//	public BigDecimal getIjid() {
//		return this.ijid;
//	}
//
//	public void setIjid(BigDecimal ijid) {
//		this.ijid = ijid;
//	}
//
//	public String getCnttNo() {
//		return this.cnttNo;
//	}
//
//	public void setCnttNo(String cnttNo) {
//		this.cnttNo = cnttNo;
//	}
//
//	public String getComposeIdno() {
//		return this.composeIdno;
//	}
//
//	public void setComposeIdno(String composeIdno) {
//		this.composeIdno = composeIdno;
//	}
//
//	public String getBilId() {
//		return this.bilId;
//	}
//
//	public void setBilId(String bilId) {
//		this.bilId = bilId;
//	}
//
//	public String getBilNo() {
//		return this.bilNo;
//	}
//
//	public void setBilNo(String bilNo) {
//		this.bilNo = bilNo;
//	}

	public Integer getPreItm() {
		return this.preItm;
	}

	public void setPreItm(Integer preItm) {
		this.preItm = preItm;
	}
//
//	public Integer getEstItm() {
//		return this.estItm;
//	}
//
//	public void setEstItm(Integer estItm) {
//		this.estItm = estItm;
//	}
//
//	public String getSpcNo() {
//		return this.spcNo;
//	}
//
//	public void setSpcNo(String spcNo) {
//		this.spcNo = spcNo;
//	}
//
//	public String getSupPrdNo() {
//		return this.supPrdNo;
//	}
//
//	public void setSupPrdNo(String supPrdNo) {
//		this.supPrdNo = supPrdNo;
//	}

	public Integer getKeyItm() {
		return this.keyItm;
	}

	public void setKeyItm(Integer keyItm) {
		this.keyItm = keyItm;
	}
//
//	public Integer getBoxItm() {
//		return this.boxItm;
//	}
//
//	public void setBoxItm(Integer boxItm) {
//		this.boxItm = boxItm;
//	}
//
//	public BigDecimal getUp() {
//		return this.up;
//	}
//
//	public void setUp(BigDecimal up) {
//		this.up = up;
//	}
//
//	public Date getValidDd() {
//		return this.validDd;
//	}
//
//	public void setValidDd(Date validDd) {
//		this.validDd = validDd;
//	}
//
//	public Date getRkDd() {
//		return this.rkDd;
//	}
//
//	public void setRkDd(Date rkDd) {
//		this.rkDd = rkDd;
//	}
//
//	public BigDecimal getAmtn() {
//		return this.amtn;
//	}
//
//	public void setAmtn(BigDecimal amtn) {
//		this.amtn = amtn;
//	}
//
//	public String getSqId() {
//		return this.sqId;
//	}
//
//	public void setSqId(String sqId) {
//		this.sqId = sqId;
//	}
//
//	public String getSqNo() {
//		return this.sqNo;
//	}
//
//	public void setSqNo(String sqNo) {
//		this.sqNo = sqNo;
//	}
//
//	public Integer getSqItm() {
//		return this.sqItm;
//	}
//
//	public void setSqItm(Integer sqItm) {
//		this.sqItm = sqItm;
//	}
//
//	public String getDepRk() {
//		return this.depRk;
//	}
//
//	public void setDepRk(String depRk) {
//		this.depRk = depRk;
//	}
//
//	public Integer getPwItm() {
//		return this.pwItm;
//	}
//
//	public void setPwItm(Integer pwItm) {
//		this.pwItm = pwItm;
//	}
//
//	public String getPrdNoSoRes() {
//		return this.prdNoSoRes;
//	}
//
//	public void setPrdNoSoRes(String prdNoSoRes) {
//		this.prdNoSoRes = prdNoSoRes;
//	}
//
//	public String getPakUnit() {
//		return this.pakUnit;
//	}
//
//	public void setPakUnit(String pakUnit) {
//		this.pakUnit = pakUnit;
//	}
//
//	public BigDecimal getPakExc() {
//		return this.pakExc;
//	}
//
//	public void setPakExc(BigDecimal pakExc) {
//		this.pakExc = pakExc;
//	}
//
//	public BigDecimal getPakNwN() {
//		return this.pakNwN;
//	}
//
//	public void setPakNwN(BigDecimal pakNwN) {
//		this.pakNwN = pakNwN;
//	}
//
//	public BigDecimal getPakNw() {
//		return this.pakNw;
//	}
//
//	public void setPakNw(BigDecimal pakNw) {
//		this.pakNw = pakNw;
//	}
//
//	public String getPakWeightUnit() {
//		return this.pakWeightUnit;
//	}
//
//	public void setPakWeightUnit(String pakWeightUnit) {
//		this.pakWeightUnit = pakWeightUnit;
//	}
//
//	public BigDecimal getPakGwN() {
//		return this.pakGwN;
//	}
//
//	public void setPakGwN(BigDecimal pakGwN) {
//		this.pakGwN = pakGwN;
//	}
//
//	public BigDecimal getPakGw() {
//		return this.pakGw;
//	}
//
//	public void setPakGw(BigDecimal pakGw) {
//		this.pakGw = pakGw;
//	}
//
//	public BigDecimal getPakMeast() {
//		return this.pakMeast;
//	}
//
//	public void setPakMeast(BigDecimal pakMeast) {
//		this.pakMeast = pakMeast;
//	}
//
//	public String getPakMeastUnit() {
//		return this.pakMeastUnit;
//	}
//
//	public void setPakMeastUnit(String pakMeastUnit) {
//		this.pakMeastUnit = pakMeastUnit;
//	}

}
